version: '3'
services:
  app:
    build: .
    container_name: application
    ports:
      - 8080:8080
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./moon.jpg:/usr/share/nginx/html/moon.jpg
    links:
      - app
    ports:
      - 8989:8989
